version: '3'
services:
  encore:
    image: encore:latest
    ports:
      - "80:8080"
    command: "java -jar /app.jar"
    restart: always
    environment:
      - TZ=Asia/Seoul
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
