version: '3'
services:
  encore-blue:
    image: encore:latest
    ports:
      - "8080:8080"
    command: "java -jar /app.jar"
    restart: always
    environment:
      - TZ=Asia/Seoul
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.blue.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: unless-stopped
